# see README.md for an explanation of these settings
[build]
target = "thumbv7m-none-eabi"
runner = ["probe-rs", "run", "--chip", "STM32F103C8Tx", "--log-format=oneline"]

# this forces the use of `flip-link` linker script
# see https://github.com/knurling-rs/flip-link for an explanation of this
[unstable]
build-std = ["core", "compiler_builtins"]
linker-flavor = "ld.lld"

[target.thumbv7m-none-eabi]
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "linker=flip-link",
]

[alias]
# `cargo rb foo` will expand to `cargo run --bin foo`
rb = "run --bin"
# `cargo rrb foo` will expand to `cargo run --release --bin foo`
rrb = "run --release --bin"
